#!/bin/bash

# Quick setup commands - run these one by one
echo "Run these commands one by one:"
echo ""
echo "# 1. Create directory structure"
echo "sudo mkdir -p /opt/azload-ml/ml_pipeline"
echo ""
echo "# 2. Set ownership"
echo "sudo chown -R \$USER:\$USER /opt/azload-ml"
echo ""
echo "# 3. Navigate to directory"
echo "cd /opt/azload-ml"
echo ""
echo "# 4. Create virtual environment"
echo "python3 -m venv venv"
echo ""
echo "# 5. Activate virtual environment"
echo "source venv/bin/activate"
echo ""
echo "# 6. Upgrade pip"
echo "pip install --upgrade pip setuptools wheel"
echo ""
echo "# 7. Create requirements.txt"
echo "cat > ml_pipeline/requirements.txt << 'EOF'"
echo "numpy==1.26.4"
echo "pandas==2.2.2"
echo "scikit-learn==1.4.2"
echo "xgboost==2.0.3"
echo "lightgbm==4.3.0"
echo "joblib==1.4.2"
echo "fastapi==0.111.0"
echo "uvicorn[standard]==0.29.0"
echo "pydantic==2.7.1"
echo "scipy==1.13.0"
echo "matplotlib==3.8.4"
echo "seaborn==0.13.2"
echo "python-dotenv==1.0.1"
echo "requests==2.31.0"
echo "setuptools>=69.0.0"
echo "wheel>=0.43.0"
echo "Cython>=3.0.10"
echo "EOF"
echo ""
echo "# 8. Install dependencies"
echo "pip install -r ml_pipeline/requirements.txt"
echo ""
echo "# 9. Verify installation"
echo "python -c 'import sklearn, pandas, numpy; print(\"✅ All packages installed successfully\")'"
